# Generated by Django 2.2.6 on 2019-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cultivar', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(blank=True, max_length=200)),
                ('repeat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'sample_info',
            },
        ),
        migrations.CreateModel(
            name='Tpm_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Entrez_Gene_ID', models.CharField(blank=True, max_length=200)),
                ('Tpm', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'tpm_list',
            },
        ),
    ]
