# Generated by Django 2.2.6 on 2019-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sample_info_tpm_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrez_Gene_ID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Entrez_Gene_ID', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Entrez_Gene_ID',
            },
        ),
        migrations.CreateModel(
            name='trans_sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SampleNo', models.CharField(blank=True, max_length=200)),
                ('ResourceName', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'trans_sample',
            },
        ),
    ]
