# Generated by Django 2.2.6 on 2019-11-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entrez_gene_id_trans_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='annot_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GeneID', models.CharField(blank=True, max_length=200)),
                ('Locus', models.CharField(blank=True, max_length=200)),
                ('Proteinproduct', models.CharField(blank=True, max_length=200)),
                ('Length', models.CharField(blank=True, max_length=200)),
                ('Proteinname', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'annot_table',
            },
        ),
    ]
